# Generated by Django 4.2.13 on 2024-05-13 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "profile_picture",
                    models.ImageField(blank=True, default="fall.png", upload_to=""),
                ),
                ("farmer_id", models.AutoField(primary_key=True, serialize=False)),
                ("contact", models.CharField(max_length=25)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "profile_picture",
                    models.ImageField(blank=True, default="fall.png", upload_to=""),
                ),
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "animal_picture",
                    models.ImageField(blank=True, default="fall.png", upload_to=""),
                ),
                ("animal_id", models.AutoField(primary_key=True, serialize=False)),
                ("animal_name", models.CharField(max_length=50)),
                ("animal_type", models.CharField(max_length=50)),
                ("animal_age", models.IntegerField()),
                ("animal_location", models.CharField(max_length=30)),
                ("animal_breed", models.CharField(max_length=20)),
                ("available", models.IntegerField()),
                ("animal_price", models.IntegerField()),
                ("animal_description", models.CharField(max_length=200)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animals",
                        to="api.farmer",
                    ),
                ),
            ],
        ),
    ]
