# Generated by Django 4.2.13 on 2024-05-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="animal_age",
            field=models.CharField(max_length=10),
        ),
    ]
